name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set environment variables
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}" >> $GITHUB_ENV
          echo "FINANCIAL_API_KEY=${{ secrets.FINANCIAL_API_KEY }}" >> $GITHUB_ENV
          echo "NEWSAPI_API_KEY=${{ secrets.NEWSAPI_API_KEY }}" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "MAIL_HOST=${{ secrets.MAIL_HOST }}" >> $GITHUB_ENV
          echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> $GITHUB_ENV
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> $GITHUB_ENV

      - name: Run tests
        run: ./gradlew test

      - name: Build the application with Gradle
        run: ./gradlew build --stacktrace

      - name: Check if JAR file exists
        run: ls -al build/libs

      - name: Build Docker Image
        run: |
          docker build -t bankapp-backend:latest -f Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: |
          docker tag bankapp-backend:latest hampuscastle/bankapp-backend:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push hampuscastle/bankapp-backend:${{ github.sha }}

      - name: Run Docker container with environment variables
        run: |
          docker run -e JWT_SECRET=${{ secrets.JWT_SECRET }} -e JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }} -e FINANCIAL_API_KEY=${{ secrets.FINANCIAL_API_KEY }} -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e MAIL_HOST=${{ secrets.MAIL_HOST }} -e MAIL_PORT=${{ secrets.MAIL_PORT }} -e MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} -e MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} hampuscastle/bankapp-backend:${{ github.sha }}